// <auto-generated />
using System;
using KargoTakipSistemi1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KargoTakipSistemi1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507100044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KargoTakipSistemi1.Models.DurumKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KargoId");

                    b.ToTable("DurumKayitlari");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Kargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Agirlik")
                        .HasColumnType("float");

                    b.Property<int>("AliciId")
                        .HasColumnType("int");

                    b.Property<int>("CikisSubeId")
                        .HasColumnType("int");

                    b.Property<int>("GondericiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KargoTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TakipNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VarisSubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AliciId");

                    b.HasIndex("CikisSubeId");

                    b.HasIndex("GondericiId");

                    b.HasIndex("VarisSubeId");

                    b.ToTable("Kargolar");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Subeler");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.DurumKaydi", b =>
                {
                    b.HasOne("KargoTakipSistemi1.Models.Kargo", "Kargo")
                        .WithMany("DurumKayitlari")
                        .HasForeignKey("KargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kargo");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Kargo", b =>
                {
                    b.HasOne("KargoTakipSistemi1.Models.Musteri", "Alici")
                        .WithMany("AlinanKargolar")
                        .HasForeignKey("AliciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KargoTakipSistemi1.Models.Sube", "CikisSube")
                        .WithMany("CikisKargolari")
                        .HasForeignKey("CikisSubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KargoTakipSistemi1.Models.Musteri", "Gonderici")
                        .WithMany("GonderilenKargolar")
                        .HasForeignKey("GondericiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KargoTakipSistemi1.Models.Sube", "VarisSube")
                        .WithMany("VarisKargolari")
                        .HasForeignKey("VarisSubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alici");

                    b.Navigation("CikisSube");

                    b.Navigation("Gonderici");

                    b.Navigation("VarisSube");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Personel", b =>
                {
                    b.HasOne("KargoTakipSistemi1.Models.Sube", "Sube")
                        .WithMany("Personeller")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Kargo", b =>
                {
                    b.Navigation("DurumKayitlari");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Musteri", b =>
                {
                    b.Navigation("AlinanKargolar");

                    b.Navigation("GonderilenKargolar");
                });

            modelBuilder.Entity("KargoTakipSistemi1.Models.Sube", b =>
                {
                    b.Navigation("CikisKargolari");

                    b.Navigation("Personeller");

                    b.Navigation("VarisKargolari");
                });
#pragma warning restore 612, 618
        }
    }
}
